import sys
import os

# Add current directory to path
sys.path.insert(0, os.path.dirname(__file__))

import io
from server import EnterpriseRESTRequestHandler, init_db, backup_db

# Initialize database just in case
init_db()

class MockSocket:
    def __init__(self, data):
        self._rfile = io.BytesIO(data)
        self._wfile = io.BytesIO()

    def makefile(self, mode='r', buffering=None, *, encoding=None, errors=None, newline=None):
        if 'r' in mode:
            return self._rfile
        else:
            return self._wfile
            
    def sendall(self, data):
        self._wfile.write(data)

class MockServer:
    def __init__(self, environ):
        self.server_address = (environ.get('SERVER_NAME', 'localhost'), environ.get('SERVER_PORT', 80))
        self.RequestHandlerClass = EnterpriseRESTRequestHandler

def application(environ, start_response):
    # Reconstruct raw HTTP Request
    path = environ.get('REQUEST_URI') or environ.get('RAW_URI') or environ.get('PATH_INFO', '/')
    if environ.get('QUERY_STRING'):
        if '?' not in path:
            path += '?' + environ['QUERY_STRING']

    request_line = f"{environ['REQUEST_METHOD']} {path} {environ.get('SERVER_PROTOCOL', 'HTTP/1.1')}\r\n"
    
    headers = ""
    for k, v in environ.items():
        if k.startswith('HTTP_'):
            header_name = k[5:].replace('_', '-').title()
            headers += f"{header_name}: {v}\r\n"
        elif k in ('CONTENT_TYPE', 'CONTENT_LENGTH') and v:
            header_name = k.replace('_', '-').title()
            headers += f"{header_name}: {v}\r\n"
    
    headers += "\r\n"
    
    body = b""
    try:
        if environ.get('CONTENT_LENGTH'):
            length = int(environ['CONTENT_LENGTH'])
            body = environ['wsgi.input'].read(length)
    except Exception:
        pass
        
    raw_request = request_line.encode('iso-8859-1') + headers.encode('iso-8859-1') + body
    
    mock_sock = MockSocket(raw_request)
    mock_server = MockServer(environ)
    client_address = (environ.get('REMOTE_ADDR', '127.0.0.1'), int(environ.get('REMOTE_PORT', 0)))
    
    # Process request
    try:
        # BaseHTTPRequestHandler calls handle() in __init__
        handler = EnterpriseRESTRequestHandler(mock_sock, client_address, mock_server)
    except Exception as e:
        import traceback
        traceback.print_exc()
        start_response('500 Internal Server Error', [('Content-Type', 'text/plain')])
        return [b'Internal Server Error']

    # Parse raw HTTP response from mock_sock._wfile
    raw_response = mock_sock._wfile.getvalue()
    
    if not raw_response:
        start_response('500 Internal Server Error', [('Content-Type', 'text/plain')])
        return [b'No response generated by handler']

    # Split headers and body
    parts = raw_response.split(b'\r\n\r\n', 1)
    header_part = parts[0]
    body_part = parts[1] if len(parts) > 1 else b""
    
    header_lines = header_part.decode('iso-8859-1').split('\r\n')
    status_line = header_lines[0]
    # status_line looks like: "HTTP/1.1 200 OK"
    # WSGI expects "200 OK"
    status = status_line.split(' ', 1)[1] if ' ' in status_line else '200 OK'
    
    response_headers = []
    for line in header_lines[1:]:
        if not line:
            continue
        if ':' in line:
            k, v = line.split(':', 1)
            response_headers.append((k.strip(), v.strip()))
            
    start_response(status, response_headers)
    return [body_part]

